spring.application.name=scouting-service

spring.datasource.url=jdbc:postgresql://localhost:5432/scoutingdb
spring.datasource.username=postgres
spring.datasource.password=tmpPass

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.enabled=true
server.port=8081
# === Keycloak Configuration ===
keycloak.auth-server-url=http://localhost:8080
keycloak.realm=scouting-realm
keycloak.resource=scout
keycloak.credentials.secret=

# === JWT for Spring Security ===
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8080/realms/scouting-realm
